### ISSUE TITLE
Consider removing peers from the peer SQL database

### ISSUE THREAD

**Issue by ungoogled1** [HDInnovations/UNIT3D-Announce#6]
Currently old/stopped peers are removed from the in memory db, but never from the sql database

**Comment by Roardom** [comment]
unit3d's cron jobs handle these the same way as they do in the PHP announce:

- https://github.com/HDInnovations/UNIT3D-Announce/blob/bcce5b2af99eb9d22d5db87507f1c90924203ffd/src/announce.rs#L673
- https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/app/Console/Commands/AutoDeleteStoppedPeers.php
- https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/app/Console/Commands/AutoFlushPeers.php

Initially, there was another queue for peer deletions, but that didn't work because if a user quickly started, stopped and started a torrent, only the most recently flushed peer state was saved.
